// <auto-generated />
namespace Eres.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class groupTimestamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(groupTimestamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201312081737029_groupTimestamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
