//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EresData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realisation
    {
        public Realisation()
        {
            this.Grades = new HashSet<Grade>();
            this.Registrations = new HashSet<Registration>();
        }
    
        public int RealisationID { get; set; }
        public int SubjectID { get; set; }
        public int SemesterID { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<Registration> Registrations { get; set; }

        public override string ToString()
        {
            return Semester.Name + " " + Subject.Name;
        }
    }
}
